<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Matikan foreign key constraint
        Schema::disableForeignKeyConstraints();

        // Hapus produk lama untuk menghindari duplikasi
        Product::truncate();

        // Nyalakan kembali foreign key constraint
        Schema::enableForeignKeyConstraints();

        // Ambil category IDs dengan slug lowercase
        $categories = Category::all()->keyBy('slug');

        // Data produk demo dengan berbagai kategori
        $products = [
            // ===== LIQUID: FREEBASE =====
            [
                'category_id' => $categories['freebase']->id,
                'kode_barang' => 'LQD-FB-001',
                'nama_barang' => 'Liquid Freebase Strawberry 30ml',
                'description' => 'Liquid freebase rasa strawberry original dengan kualitas premium dan nikotin tinggi',
                'harga_jual' => 75000,
                'harga_pokok' => 35000,
                'stok_aktual' => 50,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 10,
                'lead_time' => 3,
                'rata_penjualan' => 5,
                'is_promo' => false,
                'diskon_persen' => 0,
            ],
            [
                'category_id' => $categories['freebase']->id,
                'kode_barang' => 'LQD-FB-002',
                'nama_barang' => 'Liquid Freebase Vanilla 30ml',
                'description' => 'Liquid freebase rasa vanilla smooth dengan kandungan nikotin 18mg',
                'harga_jual' => 75000,
                'harga_pokok' => 35000,
                'stok_aktual' => 35,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 10,
                'lead_time' => 3,
                'rata_penjualan' => 4,
                'is_promo' => true,
                'diskon_persen' => 10,
            ],
            [
                'category_id' => $categories['freebase']->id,
                'kode_barang' => 'LQD-FB-003',
                'nama_barang' => 'Liquid Freebase Mango 30ml',
                'description' => 'Liquid freebase rasa mangga segar dengan sensasi throat hit kuat',
                'harga_jual' => 75000,
                'harga_pokok' => 35000,
                'stok_aktual' => 28,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 10,
                'lead_time' => 3,
                'rata_penjualan' => 6,
                'is_promo' => false,
                'diskon_persen' => 0,
            ],

            // ===== LIQUID: SALTNIC =====
            [
                'category_id' => $categories['saltnic']->id,
                'kode_barang' => 'LQD-SLT-001',
                'nama_barang' => 'Liquid Saltnic Cappuccino 30ml',
                'description' => 'Liquid saltnic rasa cappuccino premium dengan nikotin 12mg dan 20mg',
                'harga_jual' => 85000,
                'harga_pokok' => 40000,
                'stok_aktual' => 45,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 15,
                'lead_time' => 3,
                'rata_penjualan' => 7,
                'is_promo' => false,
                'diskon_persen' => 0,
            ],
            [
                'category_id' => $categories['saltnic']->id,
                'kode_barang' => 'LQD-SLT-002',
                'nama_barang' => 'Liquid Saltnic Mixed Berries 30ml',
                'description' => 'Liquid saltnic perpaduan rasa berry dengan throat hit smooth',
                'harga_jual' => 85000,
                'harga_pokok' => 40000,
                'stok_aktual' => 32,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 15,
                'lead_time' => 3,
                'rata_penjualan' => 5,
                'is_promo' => true,
                'diskon_persen' => 15,
            ],

            // ===== POD: AIO =====
            [
                'category_id' => $categories['aio']->id,
                'kode_barang' => 'POD-AIO-001',
                'nama_barang' => 'Pod AIO Vape 800 Puffs Black',
                'description' => 'Pod AIO sekali pakai dengan 800 puff dan berbagai pilihan rasa',
                'harga_jual' => 150000,
                'harga_pokok' => 65000,
                'stok_aktual' => 60,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 20,
                'lead_time' => 2,
                'rata_penjualan' => 8,
                'is_promo' => false,
                'diskon_persen' => 0,
            ],
            [
                'category_id' => $categories['aio']->id,
                'kode_barang' => 'POD-AIO-002',
                'nama_barang' => 'Pod AIO Vape 1200 Puffs White',
                'description' => 'Pod AIO premium dengan kapasitas 1200 puff dan layar digital',
                'harga_jual' => 185000,
                'harga_pokok' => 85000,
                'stok_aktual' => 42,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 15,
                'lead_time' => 2,
                'rata_penjualan' => 10,
                'is_promo' => true,
                'diskon_persen' => 8,
            ],

            // ===== POD: POD SYSTEM =====
            [
                'category_id' => $categories['pod-system']->id,
                'kode_barang' => 'POD-SYS-001',
                'nama_barang' => 'Pod System Smok Nord 5 Red',
                'description' => 'Pod system dengan teknologi airflow adjustable dan baterai 1100mAh',
                'harga_jual' => 425000,
                'harga_pokok' => 200000,
                'stok_aktual' => 25,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 8,
                'lead_time' => 5,
                'rata_penjualan' => 3,
                'is_promo' => false,
                'diskon_persen' => 0,
            ],
            [
                'category_id' => $categories['pod-system']->id,
                'kode_barang' => 'POD-SYS-002',
                'nama_barang' => 'Pod System Voopoo Drag S Gold',
                'description' => 'Pod system dengan design premium dan performa maksimal',
                'harga_jual' => 525000,
                'harga_pokok' => 280000,
                'stok_aktual' => 18,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 8,
                'lead_time' => 5,
                'rata_penjualan' => 2,
                'is_promo' => true,
                'diskon_persen' => 5,
            ],

            // ===== MOD: ELECTRICAL =====
            [
                'category_id' => $categories['electrical-mod']->id,
                'kode_barang' => 'MOD-ELC-001',
                'nama_barang' => 'Mod Electrical Geekvape L200 Black',
                'description' => 'Mod electrical dengan daya sampai 200W dan dual battery',
                'harga_jual' => 850000,
                'harga_pokok' => 450000,
                'stok_aktual' => 15,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 5,
                'lead_time' => 7,
                'rata_penjualan' => 1,
                'is_promo' => false,
                'diskon_persen' => 0,
            ],
            [
                'category_id' => $categories['electrical-mod']->id,
                'kode_barang' => 'MOD-ELC-002',
                'nama_barang' => 'Mod Electrical Vaporesso Luxe PM Silver',
                'description' => 'Mod electrical dengan display OLED dan kontrol suhu',
                'harga_jual' => 750000,
                'harga_pokok' => 400000,
                'stok_aktual' => 12,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 5,
                'lead_time' => 7,
                'rata_penjualan' => 2,
                'is_promo' => true,
                'diskon_persen' => 10,
            ],

            // ===== MOD: MECHANICAL =====
            [
                'category_id' => $categories['mechanical-mod']->id,
                'kode_barang' => 'MOD-MEC-001',
                'nama_barang' => 'Mod Mechanical Steel Brass Gold',
                'description' => 'Mod mechanical dengan material brass dan desain minimalis',
                'harga_jual' => 350000,
                'harga_pokok' => 150000,
                'stok_aktual' => 22,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 8,
                'lead_time' => 5,
                'rata_penjualan' => 2,
                'is_promo' => false,
                'diskon_persen' => 0,
            ],
            [
                'category_id' => $categories['mechanical-mod']->id,
                'kode_barang' => 'MOD-MEC-002',
                'nama_barang' => 'Mod Mechanical Steel Black Matte',
                'description' => 'Mod mechanical dengan finishing matte dan konstruksi solid',
                'harga_jual' => 320000,
                'harga_pokok' => 140000,
                'stok_aktual' => 28,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 8,
                'lead_time' => 5,
                'rata_penjualan' => 3,
                'is_promo' => true,
                'diskon_persen' => 12,
            ],

            // ===== ATOMIZER: RDA =====
            [
                'category_id' => $categories['rda']->id,
                'kode_barang' => 'ATM-RDA-001',
                'nama_barang' => 'RDA Geekvape Blitzen 25mm Silver',
                'description' => 'RDA dengan deck luas dan airflow optimal untuk cloud chasing',
                'harga_jual' => 425000,
                'harga_pokok' => 200000,
                'stok_aktual' => 18,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 6,
                'lead_time' => 4,
                'rata_penjualan' => 2,
                'is_promo' => false,
                'diskon_persen' => 0,
            ],
            [
                'category_id' => $categories['rda']->id,
                'kode_barang' => 'ATM-RDA-002',
                'nama_barang' => 'RDA Wotofo Profile 1.5 Black',
                'description' => 'RDA dengan kapasitas liquid besar dan heating area luas',
                'harga_jual' => 380000,
                'harga_pokok' => 175000,
                'stok_aktual' => 14,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 6,
                'lead_time' => 4,
                'rata_penjualan' => 1,
                'is_promo' => true,
                'diskon_persen' => 15,
            ],

            // ===== ATOMIZER: RTA =====
            [
                'category_id' => $categories['rta']->id,
                'kode_barang' => 'ATM-RTA-001',
                'nama_barang' => 'RTA Vapefly Galaxies MTL Gold',
                'description' => 'RTA untuk mouth to lung dengan airflow adjustable',
                'harga_jual' => 350000,
                'harga_pokok' => 160000,
                'stok_aktual' => 20,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 6,
                'lead_time' => 4,
                'rata_penjualan' => 3,
                'is_promo' => false,
                'diskon_persen' => 0,
            ],
            [
                'category_id' => $categories['rta']->id,
                'kode_barang' => 'ATM-RTA-002',
                'nama_barang' => 'RTA Steam Crave Aromamizer Plus Silver',
                'description' => 'RTA premium dengan kapasitas 8ml dan deck besar',
                'harga_jual' => 520000,
                'harga_pokok' => 280000,
                'stok_aktual' => 9,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 5,
                'lead_time' => 5,
                'rata_penjualan' => 1,
                'is_promo' => true,
                'diskon_persen' => 8,
            ],

            // ===== ATOMIZER: COIL PREBUILD =====
            [
                'category_id' => $categories['coil-prebuild']->id,
                'kode_barang' => 'ATM-COIL-001',
                'nama_barang' => 'Coil Prebuild Kanthal A1 0.5ohm Pack 10pcs',
                'description' => 'Coil prebuild berbahan kanthal dengan resistance 0.5ohm',
                'harga_jual' => 85000,
                'harga_pokok' => 30000,
                'stok_aktual' => 85,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 30,
                'lead_time' => 2,
                'rata_penjualan' => 15,
                'is_promo' => false,
                'diskon_persen' => 0,
            ],
            [
                'category_id' => $categories['coil-prebuild']->id,
                'kode_barang' => 'ATM-COIL-002',
                'nama_barang' => 'Coil Prebuild Stainless Steel 0.8ohm Pack 10pcs',
                'description' => 'Coil prebuild dengan dual coil design untuk flavor maksimal',
                'harga_jual' => 95000,
                'harga_pokok' => 35000,
                'stok_aktual' => 72,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 30,
                'lead_time' => 2,
                'rata_penjualan' => 12,
                'is_promo' => true,
                'diskon_persen' => 5,
            ],

            // ===== ACCESSORIES: BATTERY CELL =====
            [
                'category_id' => $categories['battery-cell']->id,
                'kode_barang' => 'ACC-BAT-001',
                'nama_barang' => 'Battery Cell Samsung 25R 18650 Original',
                'description' => 'Battery cell dengan kapasitas 2500mAh dan discharge rate tinggi',
                'harga_jual' => 125000,
                'harga_pokok' => 55000,
                'stok_aktual' => 50,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 15,
                'lead_time' => 3,
                'rata_penjualan' => 8,
                'is_promo' => false,
                'diskon_persen' => 0,
            ],
            [
                'category_id' => $categories['battery-cell']->id,
                'kode_barang' => 'ACC-BAT-002',
                'nama_barang' => 'Battery Cell LG HE4 18650 Original',
                'description' => 'Battery cell premium dengan capacity 2500mAh dan performa stabil',
                'harga_jual' => 135000,
                'harga_pokok' => 60000,
                'stok_aktual' => 42,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 15,
                'lead_time' => 3,
                'rata_penjualan' => 6,
                'is_promo' => true,
                'diskon_persen' => 10,
            ],

            // ===== ACCESSORIES: CHARGER =====
            [
                'category_id' => $categories['charger']->id,
                'kode_barang' => 'ACC-CHG-001',
                'nama_barang' => 'Charger Nitecore I2 2-slot Black',
                'description' => 'Charger intelligent dengan proteksi lengkap untuk 2 baterai',
                'harga_jual' => 185000,
                'harga_pokok' => 85000,
                'stok_aktual' => 35,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 10,
                'lead_time' => 4,
                'rata_penjualan' => 5,
                'is_promo' => false,
                'diskon_persen' => 0,
            ],
            [
                'category_id' => $categories['charger']->id,
                'kode_barang' => 'ACC-CHG-002',
                'nama_barang' => 'Charger Nitecore I4 4-slot White',
                'description' => 'Charger intelligent untuk 4 baterai dengan smart LCD display',
                'harga_jual' => 275000,
                'harga_pokok' => 125000,
                'stok_aktual' => 22,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 8,
                'lead_time' => 4,
                'rata_penjualan' => 3,
                'is_promo' => true,
                'diskon_persen' => 12,
            ],

            // ===== ACCESSORIES: COTTON =====
            [
                'category_id' => $categories['cotton']->id,
                'kode_barang' => 'ACC-CTN-001',
                'nama_barang' => 'Cotton Bacon V2 Original Pack',
                'description' => 'Cotton premium untuk wick dengan taste neutral dan durability tinggi',
                'harga_jual' => 125000,
                'harga_pokok' => 45000,
                'stok_aktual' => 95,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 30,
                'lead_time' => 2,
                'rata_penjualan' => 20,
                'is_promo' => false,
                'diskon_persen' => 0,
            ],

            // ===== ACCESSORIES: DRIPTIP =====
            [
                'category_id' => $categories['driptip']->id,
                'kode_barang' => 'ACC-DIP-001',
                'nama_barang' => 'Driptip Resin Black Pearl',
                'description' => 'Driptip dari resin dengan design ergonomis dan warna menarik',
                'harga_jual' => 85000,
                'harga_pokok' => 30000,
                'stok_aktual' => 68,
                'tgl_expired' => Carbon::now()->addYear(),
                'tgl_cukai' => Carbon::now()->addYear(),
                'nilai_ss' => 15,
                'lead_time' => 2,
                'rata_penjualan' => 12,
                'is_promo' => true,
                'diskon_persen' => 20,
            ],
        ];

        // Simpan semua produk
        foreach ($products as $product) {
            $product['slug'] = Str::slug($product['nama_barang']);
            Product::create($product);
        }
    }
}
